### ISSUE TITLE
sllurp doesn't re-send ROSPEC on reconnection?

### ISSUE THREAD

**Issue by HanYangZhao** [fviard/sllurp#1]
Hi,

I'm currently testing this fork for performance gain over the original software. I have found when the llrp reader gets rebooted, sllurp will eventually reconnect to it but not send any ROSPEC to restart the operation.  Is there a quick fix for this?

Thanks

**Comment by fviard** [comment]
Hi,
Sorry for the very long delay to reply.
I have pushed a fix for this issue.
