### ISSUE TITLE
Missing some parantheses / apostrophes in Line 4628 of llrp_proto.py

### ISSUE THREAD

**Issue by jtabb16** [fviard/sllurp#20]
Thank you for your work. I'm using this code to help me understand LLRP with the Zebra FX 7500.

Line 4628 in llrp_proto.py says: par, _ = decode_all_parameters(data[ubyte_size:], MotoFilterRule, par)

This throws an error when you run the sllurp gui because when this line of code runs, Python thinks MotoFilterRule is a variable.
MotoFilterRule should be 'MotoFilterRule', just as all the other commands have apostrophes around them.

**Comment by fviard** [comment]
Hi,
indeed you are right and it's a good catch.
Would you like to do me pull request with the fix?

Don't hesitate to report if you find other issues when using sllurp to use your Zebra reader as I don't have one to test.

**Comment by fviard** [comment]
Closing as fixed.
